//
//  PostsPresenter.swift
//  RedditPostApp
//
//  Created by Nisum on 11/17/19.
//  Copyright (c) 2019 Orlando Arzola. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PostsPresentationLogic {
    func presentView(response: Posts.RedditPosts.Response)
}

class PostsPresenter: PostsPresentationLogic {
    weak var viewController: PostsDisplayLogic?

    func presentView(response: Posts.RedditPosts.Response) {
        let posts = response.rawPosts.map {
            Posts.RedditPosts.ViewModel.DisplayedRedditPost(
                author: $0.author,
                created: "",
                thumbnailURL: $0.url,
                title: $0.title,
                commentCount: "\($0.numComments) comment\($0.numComments > 1 ? "s" : "")"
            )
        }
        let viewModel = Posts.RedditPosts.ViewModel(
            redditPosts: posts,
            loadingCount: response.showLoadingRow ? 1 : 0
        )
        viewController?.displayView(viewModel: viewModel)
    }
}
