//
//  PostsWorker.swift
//  RedditPostApp
//
//  Created by Nisum on 11/17/19.
//  Copyright (c) 2019 Orlando Arzola. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class PostsWorker {
    let apiService: RedditAPIService

    init(apiService: RedditAPIService = RedditAPI.shared) {
        self.apiService = apiService
    }

    func getPost(nextPageId: String, completion: @escaping (Result<(posts: [RedditPost], nextPageId: String), RedditError>) -> Void) {
        apiService.getPosts(
            limit: "15",
            nextPageId: nextPageId,
            completion: { result in
                switch result {
                case .success(let postResponse):
                    let redditPosts = postResponse.data.children.compactMap{ $0.data }
                    completion(.success((posts: redditPosts, nextPageId: postResponse.data.after)))
                case .failure(let error):
                    completion(.failure(error))
                }
        }
        )
    }
}
