//
//  PostsInteractor.swift
//  RedditPostApp
//
//  Created by Nisum on 11/17/19.
//  Copyright (c) 2019 Orlando Arzola. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PostsBusinessLogic {
    func getPosts(request: Posts.RedditPosts.Request)
}

protocol PostsDataStore {
}

class PostsInteractor: PostsBusinessLogic, PostsDataStore {
    var presenter: PostsPresentationLogic?
    var worker = PostsWorker()

    var nextPageId = ""
    var isFetchingPosts = false

    func getPosts(request: Posts.RedditPosts.Request) {
        worker.getPost(nextPageId: request.pageId) { [weak self] result in
            switch result {
            case .success(let response):
                self?.nextPageId = response.nextPageId
                let response = Posts.RedditPosts.Response(rawPosts: response.posts)
                self?.presenter?.presentView(response: response)
            case .failure(let error):
                print(error.localizedDescription)
            }
        }
    }
}
