//
//  PostsModels.swift
//  RedditPostApp
//
//  Created by Nisum on 11/17/19.
//  Copyright (c) 2019 Orlando Arzola. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Posts {
    // MARK: Use cases

    enum RedditPosts {
        struct Request {
            var pageId: String
        }
        struct Response {
            var rawPosts: [RedditPost]
            var showLoadingRow: Bool
        }
        struct ViewModel {
            struct DisplayedRedditPost {
                let id: String
                let author: String
                let created: String
                let thumbnailURL: String?
                let title: String
                let commentCount: String
            }

            let redditPosts: [DisplayedRedditPost]
            let loadingCount: Int
        }
    }
}
