//
//  WelcomeWorker.swift
//  RedditPostApp
//
//  Created by Nisum on 11/17/19.
//  Copyright (c) 2019 Orlando Arzola. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class WelcomeWorker {

    let apiService: RedditAPIService

    init(apiService: RedditAPIService = RedditAPI.shared) {
        self.apiService = apiService
    }

    func login(completion: @escaping (Result<Void, RedditError>) -> Void) {
        apiService.getToken(completion: completion)
    }
}
