//
//  WelcomeViewController.swift
//  RedditPostApp
//
//  Created by Nisum on 11/17/19.
//  Copyright (c) 2019 Orlando Arzola. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WelcomeDisplayLogic: class {
    func displayPosts()
    func displayError()
    func displayLoading()
    func hideLoading()
}

class WelcomeViewController: UIViewController, WelcomeDisplayLogic {
    var interactor: WelcomeBusinessLogic?
    var router: (NSObjectProtocol & WelcomeRoutingLogic & WelcomeDataPassing)?

    @IBOutlet weak var loginButton: UIButton!
    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: Setup

    private func setup() {
        let viewController = self
        let interactor = WelcomeInteractor()
        let presenter = WelcomePresenter()
        let router = WelcomeRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        setupViews()
    }

    // MARK: Helper Methods

    @IBAction func loginButtonWasPressed(_ sender: Any) {
        interactor?.login()
    }


    func setupViews() {
        title = "Login"
    }

    // MARK: VIP Methods

    func displayPosts() {
        router?.routeToPosts()
    }

    func displayError() {
        loginButton.setTitle("Try Again", for: .normal)
    }

    func displayLoading() {
        loginButton.setTitle("Loading...", for: .normal)
    }

    func hideLoading() {
        loginButton.setTitle("Login", for: .normal)
    }
}
