//
//  WelcomeRouter.swift
//  RedditPostApp
//
//  Created by Nisum on 11/17/19.
//  Copyright (c) 2019 Orlando Arzola. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol WelcomeRoutingLogic {
    func routeToPosts()
}

protocol WelcomeDataPassing {
    var dataStore: WelcomeDataStore? { get }
}

class WelcomeRouter: NSObject, WelcomeRoutingLogic, WelcomeDataPassing {
    weak var viewController: WelcomeViewController?
    var dataStore: WelcomeDataStore?

    let mainStoryBoard = UIStoryboard(name: "Main", bundle: nil)

    // MARK: Routing

    func routeToPosts() {
        let destinationVC = mainStoryBoard.instantiateViewController(withIdentifier: "PostsViewController") as! PostsViewController
        viewController?.navigationController?.pushViewController(
            destinationVC,
            animated: true
        )
    }
}
